// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto

package transformation

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	transformation "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/transformation"
	matchers "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/core/matchers"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResponseMatch struct {
	Matchers               []*matchers.HeaderMatcher      `protobuf:"bytes,1,rep,name=matchers,proto3" json:"matchers,omitempty"`
	ResponseCodeDetails    string                         `protobuf:"bytes,2,opt,name=response_code_details,json=responseCodeDetails,proto3" json:"response_code_details,omitempty"`
	ResponseTransformation *transformation.Transformation `protobuf:"bytes,3,opt,name=response_transformation,json=responseTransformation,proto3" json:"response_transformation,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                       `json:"-"`
	XXX_unrecognized       []byte                         `json:"-"`
	XXX_sizecache          int32                          `json:"-"`
}

func (m *ResponseMatch) Reset()         { *m = ResponseMatch{} }
func (m *ResponseMatch) String() string { return proto.CompactTextString(m) }
func (*ResponseMatch) ProtoMessage()    {}
func (*ResponseMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8def6c8e0694580, []int{0}
}
func (m *ResponseMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMatch.Unmarshal(m, b)
}
func (m *ResponseMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMatch.Marshal(b, m, deterministic)
}
func (m *ResponseMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMatch.Merge(m, src)
}
func (m *ResponseMatch) XXX_Size() int {
	return xxx_messageInfo_ResponseMatch.Size(m)
}
func (m *ResponseMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMatch.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMatch proto.InternalMessageInfo

func (m *ResponseMatch) GetMatchers() []*matchers.HeaderMatcher {
	if m != nil {
		return m.Matchers
	}
	return nil
}

func (m *ResponseMatch) GetResponseCodeDetails() string {
	if m != nil {
		return m.ResponseCodeDetails
	}
	return ""
}

func (m *ResponseMatch) GetResponseTransformation() *transformation.Transformation {
	if m != nil {
		return m.ResponseTransformation
	}
	return nil
}

type Transformations struct {
	// Apply a transformation to requests.
	RequestTransformation *transformation.Transformation `protobuf:"bytes,1,opt,name=request_transformation,json=requestTransformation,proto3" json:"request_transformation,omitempty"`
	// Clear the route cache if the request transformation was applied.
	ClearRouteCache bool `protobuf:"varint,3,opt,name=clear_route_cache,json=clearRouteCache,proto3" json:"clear_route_cache,omitempty"`
	// Apply a transformation to responses.
	ResponseTransformation *transformation.Transformation `protobuf:"bytes,2,opt,name=response_transformation,json=responseTransformation,proto3" json:"response_transformation,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                       `json:"-"`
	XXX_unrecognized       []byte                         `json:"-"`
	XXX_sizecache          int32                          `json:"-"`
}

func (m *Transformations) Reset()         { *m = Transformations{} }
func (m *Transformations) String() string { return proto.CompactTextString(m) }
func (*Transformations) ProtoMessage()    {}
func (*Transformations) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8def6c8e0694580, []int{1}
}
func (m *Transformations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transformations.Unmarshal(m, b)
}
func (m *Transformations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transformations.Marshal(b, m, deterministic)
}
func (m *Transformations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transformations.Merge(m, src)
}
func (m *Transformations) XXX_Size() int {
	return xxx_messageInfo_Transformations.Size(m)
}
func (m *Transformations) XXX_DiscardUnknown() {
	xxx_messageInfo_Transformations.DiscardUnknown(m)
}

var xxx_messageInfo_Transformations proto.InternalMessageInfo

func (m *Transformations) GetRequestTransformation() *transformation.Transformation {
	if m != nil {
		return m.RequestTransformation
	}
	return nil
}

func (m *Transformations) GetClearRouteCache() bool {
	if m != nil {
		return m.ClearRouteCache
	}
	return false
}

func (m *Transformations) GetResponseTransformation() *transformation.Transformation {
	if m != nil {
		return m.ResponseTransformation
	}
	return nil
}

type EarlyTransformations struct {
	ResponseTransforms   []*ResponseMatch `protobuf:"bytes,1,rep,name=response_transforms,json=responseTransforms,proto3" json:"response_transforms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EarlyTransformations) Reset()         { *m = EarlyTransformations{} }
func (m *EarlyTransformations) String() string { return proto.CompactTextString(m) }
func (*EarlyTransformations) ProtoMessage()    {}
func (*EarlyTransformations) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8def6c8e0694580, []int{2}
}
func (m *EarlyTransformations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EarlyTransformations.Unmarshal(m, b)
}
func (m *EarlyTransformations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EarlyTransformations.Marshal(b, m, deterministic)
}
func (m *EarlyTransformations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EarlyTransformations.Merge(m, src)
}
func (m *EarlyTransformations) XXX_Size() int {
	return xxx_messageInfo_EarlyTransformations.Size(m)
}
func (m *EarlyTransformations) XXX_DiscardUnknown() {
	xxx_messageInfo_EarlyTransformations.DiscardUnknown(m)
}

var xxx_messageInfo_EarlyTransformations proto.InternalMessageInfo

func (m *EarlyTransformations) GetResponseTransforms() []*ResponseMatch {
	if m != nil {
		return m.ResponseTransforms
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseMatch)(nil), "transformation.options.gloo.solo.io.ResponseMatch")
	proto.RegisterType((*Transformations)(nil), "transformation.options.gloo.solo.io.Transformations")
	proto.RegisterType((*EarlyTransformations)(nil), "transformation.options.gloo.solo.io.EarlyTransformations")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto", fileDescriptor_d8def6c8e0694580)
}

var fileDescriptor_d8def6c8e0694580 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xd6, 0xa6, 0x08, 0x15, 0x57, 0xa8, 0xc2, 0xfd, 0x21, 0xca, 0xa1, 0x8a, 0xca, 0x25, 0x20,
	0x61, 0x8b, 0x45, 0xe2, 0x01, 0x28, 0x15, 0x5c, 0x7a, 0x60, 0xd5, 0x03, 0xe2, 0xb2, 0x72, 0x9c,
	0xc9, 0xc6, 0xe0, 0xec, 0x98, 0xb1, 0x13, 0x52, 0x71, 0xe2, 0x6d, 0x78, 0x04, 0x9e, 0x87, 0x3b,
	0x47, 0xee, 0xc8, 0xbb, 0x9b, 0x48, 0xbb, 0x55, 0xa3, 0x20, 0x71, 0xf3, 0x7c, 0xe3, 0x6f, 0xe6,
	0x9b, 0x4f, 0x33, 0xec, 0x43, 0x61, 0xc2, 0x6c, 0x31, 0x16, 0x1a, 0xe7, 0xd2, 0xa3, 0xc5, 0xe7,
	0x06, 0x65, 0x61, 0x11, 0xa5, 0x23, 0xfc, 0x04, 0x3a, 0xf8, 0x3a, 0x52, 0xce, 0xc8, 0xe5, 0x0b,
	0x89, 0x2e, 0x18, 0x2c, 0xbd, 0x0c, 0xa4, 0x4a, 0x3f, 0x45, 0x9a, 0xab, 0x18, 0x77, 0x42, 0xe1,
	0x08, 0x03, 0xf2, 0x27, 0x1d, 0xb4, 0xe1, 0x8a, 0x58, 0x4f, 0xc4, 0x56, 0xc2, 0xe0, 0xe0, 0xac,
	0x40, 0x2c, 0x2c, 0xc8, 0x8a, 0x32, 0x5e, 0x4c, 0xe5, 0x57, 0x52, 0xce, 0x01, 0xf9, 0xba, 0xc8,
	0xe0, 0xd5, 0xdd, 0x5a, 0x34, 0x12, 0xc8, 0xb9, 0x0a, 0x7a, 0x06, 0xe4, 0x37, 0x8f, 0x86, 0x77,
	0x7d, 0x07, 0x0f, 0x56, 0x01, 0xa8, 0x54, 0x56, 0x42, 0xb9, 0xc4, 0x9b, 0x2a, 0x2c, 0xfd, 0xae,
	0x23, 0x0d, 0x8e, 0x0b, 0x2c, 0xb0, 0x7a, 0xca, 0xf8, 0x6a, 0x50, 0x0e, 0xab, 0x50, 0x83, 0xb0,
	0x0a, 0x35, 0x76, 0xfe, 0x3b, 0x61, 0x0f, 0x33, 0xf0, 0x0e, 0x4b, 0x0f, 0x57, 0x51, 0x1a, 0xbf,
	0x64, 0xfb, 0x6b, 0x8d, 0xfd, 0x64, 0xb8, 0x37, 0x3a, 0x48, 0x9f, 0x8a, 0x8d, 0xe8, 0x38, 0x4b,
	0xcb, 0x18, 0xf1, 0x0e, 0xd4, 0x04, 0xe8, 0xaa, 0xfe, 0x90, 0x6d, 0xa8, 0x3c, 0x65, 0x27, 0xd4,
	0xd4, 0xcd, 0x35, 0x4e, 0x20, 0x9f, 0x40, 0x50, 0xc6, 0xfa, 0x7e, 0x6f, 0x98, 0x8c, 0x1e, 0x64,
	0x47, 0xeb, 0xe4, 0x05, 0x4e, 0xe0, 0x4d, 0x9d, 0xe2, 0x8a, 0x3d, 0xde, 0x70, 0xda, 0x73, 0xf5,
	0xf7, 0x86, 0xc9, 0xe8, 0x20, 0x1d, 0x89, 0xca, 0x0e, 0xa1, 0x9c, 0x11, 0xcb, 0x54, 0x4c, 0x8d,
	0x0d, 0x40, 0x62, 0x16, 0x82, 0x13, 0xd7, 0xad, 0xff, 0xd9, 0xe9, 0xba, 0x50, 0x1b, 0x3f, 0xff,
	0xde, 0x63, 0x87, 0x6d, 0xc8, 0xf3, 0x9c, 0x9d, 0x12, 0x7c, 0x59, 0x80, 0x0f, 0xdd, 0xae, 0xc9,
	0x3f, 0x76, 0x3d, 0x69, 0xea, 0xb4, 0x61, 0xfe, 0x8c, 0x3d, 0xd2, 0x16, 0x14, 0xe5, 0x84, 0x8b,
	0x00, 0xb9, 0x56, 0x7a, 0x06, 0xd5, 0x44, 0xfb, 0xd9, 0x61, 0x95, 0xc8, 0x22, 0x7e, 0x11, 0xe1,
	0x6d, 0x1e, 0xf4, 0xfe, 0x93, 0x07, 0xdf, 0xd8, 0xf1, 0xa5, 0x22, 0x7b, 0xd3, 0xf5, 0x41, 0xb3,
	0xa3, 0xdb, 0xad, 0xd7, 0x4b, 0x90, 0x8a, 0x1d, 0xce, 0x44, 0xb4, 0x56, 0x29, 0xe3, 0xb7, 0x04,
	0xf8, 0xd7, 0xef, 0x7f, 0xfe, 0xb9, 0x97, 0xfc, 0xf8, 0x75, 0x96, 0x7c, 0x7c, 0xbb, 0xdb, 0x45,
	0xbb, 0xcf, 0xc5, 0xf6, 0xab, 0x1e, 0xdf, 0xaf, 0x56, 0xf9, 0xe5, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xaa, 0xb4, 0x32, 0xd4, 0x23, 0x04, 0x00, 0x00,
}

func (this *ResponseMatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseMatch)
	if !ok {
		that2, ok := that.(ResponseMatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Matchers) != len(that1.Matchers) {
		return false
	}
	for i := range this.Matchers {
		if !this.Matchers[i].Equal(that1.Matchers[i]) {
			return false
		}
	}
	if this.ResponseCodeDetails != that1.ResponseCodeDetails {
		return false
	}
	if !this.ResponseTransformation.Equal(that1.ResponseTransformation) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Transformations) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Transformations)
	if !ok {
		that2, ok := that.(Transformations)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RequestTransformation.Equal(that1.RequestTransformation) {
		return false
	}
	if this.ClearRouteCache != that1.ClearRouteCache {
		return false
	}
	if !this.ResponseTransformation.Equal(that1.ResponseTransformation) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *EarlyTransformations) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EarlyTransformations)
	if !ok {
		that2, ok := that.(EarlyTransformations)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.ResponseTransforms) != len(that1.ResponseTransforms) {
		return false
	}
	for i := range this.ResponseTransforms {
		if !this.ResponseTransforms[i].Equal(that1.ResponseTransforms[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
