// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/options.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	v2 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/config/filter/http/gzip/v2"
	v3 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/filters/http/buffer/v3"
	proxylatency "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/proxylatency"
	_ "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/transformation"
	dlp "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/options/dlp"
	v1 "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/options/extauth/v1"
	jwt "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/options/jwt"
	ratelimit "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/options/ratelimit"
	rbac "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/options/rbac"
	waf "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/options/waf"
	als "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/als"
	aws "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/aws"
	azure "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/azure"
	cors "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/cors"
	faultinjection "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/faultinjection"
	grpc "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/grpc"
	grpc_web "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/grpc_web"
	hcm "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/hcm"
	headers "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/headers"
	healthcheck "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/healthcheck"
	lbhash "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/lbhash"
	protocol_upgrade "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/protocol_upgrade"
	rest "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/rest"
	retries "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/retries"
	shadowing "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/shadowing"
	stats "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/stats"
	tcp "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/tcp"
	tracing "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/tracing"
	transformation "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/transformation"
	wasm "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/options/wasm"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Optional, feature-specific configuration that lives on gateways.
// Each ListenerOption object contains configuration for a specific feature.
// Note to developers: new Listener plugins must be added to this struct
// to be usable by Gloo. (plugins currently need to be compiled into Gloo)
type ListenerOptions struct {
	AccessLoggingService *als.AccessLoggingService `protobuf:"bytes,1,opt,name=access_logging_service,json=accessLoggingService,proto3" json:"access_logging_service,omitempty"`
	// Extensions will be passed along from Listeners, Gateways, VirtualServices, Routes, and Route tables to the
	// underlying Proxy, making them useful for controllers, validation tools, etc. which interact with kubernetes yaml.
	//
	// Some sample use cases:
	// * controllers, deployment pipelines, helm charts, etc. which wish to use extensions as a kind of opaque metadata.
	// * In the future, Gloo may support gRPC-based plugins which communicate with the Gloo translator out-of-process.
	// Opaque Extensions enables development of out-of-process plugins without requiring recompiling & redeploying Gloo's API.
	Extensions *Extensions `protobuf:"bytes,2,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// Soft limit on size of the listener's new connection read and write buffers. If unspecified, defaults to 1MiB
	// For more info, check out the [Envoy docs](https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v2/api/v2/listener.proto)
	PerConnectionBufferLimitBytes *types.UInt32Value `protobuf:"bytes,3,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes,proto3" json:"per_connection_buffer_limit_bytes,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}           `json:"-"`
	XXX_unrecognized              []byte             `json:"-"`
	XXX_sizecache                 int32              `json:"-"`
}

func (m *ListenerOptions) Reset()         { *m = ListenerOptions{} }
func (m *ListenerOptions) String() string { return proto.CompactTextString(m) }
func (*ListenerOptions) ProtoMessage()    {}
func (*ListenerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{0}
}
func (m *ListenerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerOptions.Unmarshal(m, b)
}
func (m *ListenerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerOptions.Marshal(b, m, deterministic)
}
func (m *ListenerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerOptions.Merge(m, src)
}
func (m *ListenerOptions) XXX_Size() int {
	return xxx_messageInfo_ListenerOptions.Size(m)
}
func (m *ListenerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerOptions proto.InternalMessageInfo

func (m *ListenerOptions) GetAccessLoggingService() *als.AccessLoggingService {
	if m != nil {
		return m.AccessLoggingService
	}
	return nil
}

func (m *ListenerOptions) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *ListenerOptions) GetPerConnectionBufferLimitBytes() *types.UInt32Value {
	if m != nil {
		return m.PerConnectionBufferLimitBytes
	}
	return nil
}

// Optional, feature-specific configuration that lives on http listeners
type HttpListenerOptions struct {
	GrpcWeb                       *grpc_web.GrpcWeb                  `protobuf:"bytes,1,opt,name=grpc_web,json=grpcWeb,proto3" json:"grpc_web,omitempty"`
	HttpConnectionManagerSettings *hcm.HttpConnectionManagerSettings `protobuf:"bytes,2,opt,name=http_connection_manager_settings,json=httpConnectionManagerSettings,proto3" json:"http_connection_manager_settings,omitempty"`
	// enable [Envoy health checks](https://www.envoyproxy.io/docs/envoy/v1.7.0/api-v2/config/filter/http/health_check/v2/health_check.proto) on this listener
	HealthCheck *healthcheck.HealthCheck `protobuf:"bytes,4,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	// Extensions will be passed along from Listeners, Gateways, VirtualServices, Routes, and Route tables to the
	// underlying Proxy, making them useful for controllers, validation tools, etc. which interact with kubernetes yaml.
	//
	// Some sample use cases:
	// * controllers, deployment pipelines, helm charts, etc. which wish to use extensions as a kind of opaque metadata.
	// * In the future, Gloo may support gRPC-based plugins which communicate with the Gloo translator out-of-process.
	// Opaque Extensions enables development of out-of-process plugins without requiring recompiling & redeploying Gloo's API.
	Extensions *Extensions `protobuf:"bytes,3,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// Enterprise-only: Config for Web Application Firewall (WAF), supporting
	// the popular ModSecurity 3.0 ruleset
	Waf *waf.Settings `protobuf:"bytes,5,opt,name=waf,proto3" json:"waf,omitempty"`
	// Enterprise-only: Config for data loss prevention
	Dlp *dlp.FilterConfig `protobuf:"bytes,6,opt,name=dlp,proto3" json:"dlp,omitempty"`
	// Wasm filter config [very-experimental!]
	// Currently these extensions will only work if Gloo deployed using the helm flag, wasm.enabled=true
	// These require a special nightly version of envoy which is not deployed by default
	Wasm *wasm.PluginSource `protobuf:"bytes,7,opt,name=wasm,proto3" json:"wasm,omitempty"`
	// Enterprise-only: External auth related settings
	Extauth *v1.Settings `protobuf:"bytes,10,opt,name=extauth,proto3" json:"extauth,omitempty"`
	// Enterprise-only: Settings for the rate limiting server itself
	RatelimitServer *ratelimit.Settings `protobuf:"bytes,11,opt,name=ratelimit_server,json=ratelimitServer,proto3" json:"ratelimit_server,omitempty"`
	// Gzip is an HTTP option which enables Gloo to compress
	// data returned from an upstream service upon client request.
	// Compression is useful in situations where large payloads need to be transmitted without compromising the response time.
	// Example:
	// ```
	// gzip:
	//  contentType:
	//  - "application/json"
	//  compressionLevel: BEST
	// ```
	Gzip *v2.Gzip `protobuf:"bytes,8,opt,name=gzip,proto3" json:"gzip,omitempty"`
	// Enterprise-only: Proxy latency
	ProxyLatency *proxylatency.ProxyLatency `protobuf:"bytes,9,opt,name=proxy_latency,json=proxyLatency,proto3" json:"proxy_latency,omitempty"`
	// Buffer can be used to set the maximum request size
	// that the filter will buffer before the connection
	// manager will stop buffering and return a 413 response.
	Buffer               *v3.Buffer `protobuf:"bytes,12,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HttpListenerOptions) Reset()         { *m = HttpListenerOptions{} }
func (m *HttpListenerOptions) String() string { return proto.CompactTextString(m) }
func (*HttpListenerOptions) ProtoMessage()    {}
func (*HttpListenerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{1}
}
func (m *HttpListenerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpListenerOptions.Unmarshal(m, b)
}
func (m *HttpListenerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpListenerOptions.Marshal(b, m, deterministic)
}
func (m *HttpListenerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpListenerOptions.Merge(m, src)
}
func (m *HttpListenerOptions) XXX_Size() int {
	return xxx_messageInfo_HttpListenerOptions.Size(m)
}
func (m *HttpListenerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpListenerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_HttpListenerOptions proto.InternalMessageInfo

func (m *HttpListenerOptions) GetGrpcWeb() *grpc_web.GrpcWeb {
	if m != nil {
		return m.GrpcWeb
	}
	return nil
}

func (m *HttpListenerOptions) GetHttpConnectionManagerSettings() *hcm.HttpConnectionManagerSettings {
	if m != nil {
		return m.HttpConnectionManagerSettings
	}
	return nil
}

func (m *HttpListenerOptions) GetHealthCheck() *healthcheck.HealthCheck {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

func (m *HttpListenerOptions) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *HttpListenerOptions) GetWaf() *waf.Settings {
	if m != nil {
		return m.Waf
	}
	return nil
}

func (m *HttpListenerOptions) GetDlp() *dlp.FilterConfig {
	if m != nil {
		return m.Dlp
	}
	return nil
}

func (m *HttpListenerOptions) GetWasm() *wasm.PluginSource {
	if m != nil {
		return m.Wasm
	}
	return nil
}

func (m *HttpListenerOptions) GetExtauth() *v1.Settings {
	if m != nil {
		return m.Extauth
	}
	return nil
}

func (m *HttpListenerOptions) GetRatelimitServer() *ratelimit.Settings {
	if m != nil {
		return m.RatelimitServer
	}
	return nil
}

func (m *HttpListenerOptions) GetGzip() *v2.Gzip {
	if m != nil {
		return m.Gzip
	}
	return nil
}

func (m *HttpListenerOptions) GetProxyLatency() *proxylatency.ProxyLatency {
	if m != nil {
		return m.ProxyLatency
	}
	return nil
}

func (m *HttpListenerOptions) GetBuffer() *v3.Buffer {
	if m != nil {
		return m.Buffer
	}
	return nil
}

// Optional, feature-specific configuration that lives on tcp listeners
type TcpListenerOptions struct {
	TcpProxySettings     *tcp.TcpProxySettings `protobuf:"bytes,3,opt,name=tcp_proxy_settings,json=tcpProxySettings,proto3" json:"tcp_proxy_settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TcpListenerOptions) Reset()         { *m = TcpListenerOptions{} }
func (m *TcpListenerOptions) String() string { return proto.CompactTextString(m) }
func (*TcpListenerOptions) ProtoMessage()    {}
func (*TcpListenerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{2}
}
func (m *TcpListenerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpListenerOptions.Unmarshal(m, b)
}
func (m *TcpListenerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpListenerOptions.Marshal(b, m, deterministic)
}
func (m *TcpListenerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpListenerOptions.Merge(m, src)
}
func (m *TcpListenerOptions) XXX_Size() int {
	return xxx_messageInfo_TcpListenerOptions.Size(m)
}
func (m *TcpListenerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpListenerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TcpListenerOptions proto.InternalMessageInfo

func (m *TcpListenerOptions) GetTcpProxySettings() *tcp.TcpProxySettings {
	if m != nil {
		return m.TcpProxySettings
	}
	return nil
}

// Optional, feature-specific configuration that lives on virtual hosts.
// Each VirtualHostPlugin object contains configuration for a specific feature.
// Note to developers: new Virtual Host plugins must be added to this struct
// to be usable by Gloo. (plugins currently need to be compiled into Gloo)
type VirtualHostOptions struct {
	// Extensions will be passed along from Listeners, Gateways, VirtualServices, Routes, and Route tables to the
	// underlying Proxy, making them useful for controllers, validation tools, etc. which interact with kubernetes yaml.
	//
	// Some sample use cases:
	// * controllers, deployment pipelines, helm charts, etc. which wish to use extensions as a kind of opaque metadata.
	// * In the future, Gloo may support gRPC-based plugins which communicate with the Gloo translator out-of-process.
	// Opaque Extensions enables development of out-of-process plugins without requiring recompiling & redeploying Gloo's API.
	Extensions *Extensions          `protobuf:"bytes,1,opt,name=extensions,proto3" json:"extensions,omitempty"`
	Retries    *retries.RetryPolicy `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Stats      *stats.Stats         `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	// Append/Remove headers on Requests or Responses on all routes contained in this Virtual Host
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,2,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Defines a CORS policy for the virtual host
	// If a CORS policy is also defined on the route matched by the request, the policies are merged.
	Cors *cors.CorsPolicy `protobuf:"bytes,3,opt,name=cors,proto3" json:"cors,omitempty"`
	// Transformations to apply
	Transformations *transformation.Transformations `protobuf:"bytes,4,opt,name=transformations,proto3" json:"transformations,omitempty"`
	// Enterprise-only: Config for GlooE rate-limiting using simplified (gloo-specific) API
	RatelimitBasic *ratelimit.IngressRateLimit `protobuf:"bytes,6,opt,name=ratelimit_basic,json=ratelimitBasic,proto3" json:"ratelimit_basic,omitempty"`
	// Enterprise-only: Partial config for GlooE rate-limiting based on Envoy's rate-limit service;
	// supports Envoy's rate-limit service API. (reference here: https://github.com/lyft/ratelimit#configuration)
	// Configure rate-limit *actions* here, which define how request characteristics get translated into
	// descriptors used by the rate-limit service for rate-limiting. Configure rate-limit *descriptors* and
	// their associated limits on the Gloo settings
	Ratelimit *ratelimit.RateLimitVhostExtension `protobuf:"bytes,7,opt,name=ratelimit,proto3" json:"ratelimit,omitempty"`
	// Enterprise-only: Config for Web Application Firewall (WAF), supporting
	// the popular ModSecurity 3.0 ruleset
	Waf *waf.Settings `protobuf:"bytes,8,opt,name=waf,proto3" json:"waf,omitempty"`
	// Enterprise-only: Config for reading and verifying JWTs. Copy verifiable information from JWTs into other
	// headers to make routing decisions or combine with RBAC for fine-grained access control.
	Jwt *jwt.VhostExtension `protobuf:"bytes,9,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// Enterprise-only: Config for RBAC (currently only supports RBAC based on JWT claims)
	Rbac *rbac.ExtensionSettings `protobuf:"bytes,11,opt,name=rbac,proto3" json:"rbac,omitempty"`
	// Enterprise-only: Authentication configuration
	Extauth *v1.ExtAuthExtension `protobuf:"bytes,12,opt,name=extauth,proto3" json:"extauth,omitempty"`
	// Enterprise-only: Config for data loss prevention
	Dlp *dlp.Config `protobuf:"bytes,13,opt,name=dlp,proto3" json:"dlp,omitempty"`
	// BufferPerRoute can be used to set the maximum request size
	// that the filter will buffer before the connection
	// manager will stop buffering and return a 413 response.
	// Note: If you have not set a global config (at the gateway level), this
	// override will not do anything by itself.
	BufferPerRoute *v3.BufferPerRoute `protobuf:"bytes,14,opt,name=buffer_per_route,json=bufferPerRoute,proto3" json:"buffer_per_route,omitempty"`
	// Early transformations stage. These transformations run before most other options are processed.
	StagedTransformations *transformation.TransformationStages `protobuf:"bytes,15,opt,name=staged_transformations,json=stagedTransformations,proto3" json:"staged_transformations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *VirtualHostOptions) Reset()         { *m = VirtualHostOptions{} }
func (m *VirtualHostOptions) String() string { return proto.CompactTextString(m) }
func (*VirtualHostOptions) ProtoMessage()    {}
func (*VirtualHostOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{3}
}
func (m *VirtualHostOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualHostOptions.Unmarshal(m, b)
}
func (m *VirtualHostOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualHostOptions.Marshal(b, m, deterministic)
}
func (m *VirtualHostOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualHostOptions.Merge(m, src)
}
func (m *VirtualHostOptions) XXX_Size() int {
	return xxx_messageInfo_VirtualHostOptions.Size(m)
}
func (m *VirtualHostOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualHostOptions.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualHostOptions proto.InternalMessageInfo

func (m *VirtualHostOptions) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *VirtualHostOptions) GetRetries() *retries.RetryPolicy {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *VirtualHostOptions) GetStats() *stats.Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *VirtualHostOptions) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *VirtualHostOptions) GetCors() *cors.CorsPolicy {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *VirtualHostOptions) GetTransformations() *transformation.Transformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

func (m *VirtualHostOptions) GetRatelimitBasic() *ratelimit.IngressRateLimit {
	if m != nil {
		return m.RatelimitBasic
	}
	return nil
}

func (m *VirtualHostOptions) GetRatelimit() *ratelimit.RateLimitVhostExtension {
	if m != nil {
		return m.Ratelimit
	}
	return nil
}

func (m *VirtualHostOptions) GetWaf() *waf.Settings {
	if m != nil {
		return m.Waf
	}
	return nil
}

func (m *VirtualHostOptions) GetJwt() *jwt.VhostExtension {
	if m != nil {
		return m.Jwt
	}
	return nil
}

func (m *VirtualHostOptions) GetRbac() *rbac.ExtensionSettings {
	if m != nil {
		return m.Rbac
	}
	return nil
}

func (m *VirtualHostOptions) GetExtauth() *v1.ExtAuthExtension {
	if m != nil {
		return m.Extauth
	}
	return nil
}

func (m *VirtualHostOptions) GetDlp() *dlp.Config {
	if m != nil {
		return m.Dlp
	}
	return nil
}

func (m *VirtualHostOptions) GetBufferPerRoute() *v3.BufferPerRoute {
	if m != nil {
		return m.BufferPerRoute
	}
	return nil
}

func (m *VirtualHostOptions) GetStagedTransformations() *transformation.TransformationStages {
	if m != nil {
		return m.StagedTransformations
	}
	return nil
}

// Optional, feature-specific configuration that lives on routes.
// Each RouteOption object contains configuration for a specific feature.
// Note to developers: new Route plugins must be added to this struct
// to be usable by Gloo. (plugins currently need to be compiled into Gloo)
type RouteOptions struct {
	// Transformations to apply
	Transformations *transformation.Transformations `protobuf:"bytes,1,opt,name=transformations,proto3" json:"transformations,omitempty"`
	Faults          *faultinjection.RouteFaults     `protobuf:"bytes,2,opt,name=faults,proto3" json:"faults,omitempty"`
	// For requests matched on this route, rewrite the HTTP request path to the provided value before forwarding upstream
	PrefixRewrite *types.StringValue `protobuf:"bytes,3,opt,name=prefix_rewrite,json=prefixRewrite,proto3" json:"prefix_rewrite,omitempty"`
	// Specifies the upstream timeout for the route. If not specified, the default is 15s. This spans between the point
	// at which the entire downstream request (i.e. end-of-stream) has been processed and when the upstream response has
	// been completely processed. A value of 0 will disable the route’s timeout.
	Timeout *time.Duration       `protobuf:"bytes,4,opt,name=timeout,proto3,stdduration" json:"timeout,omitempty"`
	Retries *retries.RetryPolicy `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	// Extensions will be passed along from Listeners, Gateways, VirtualServices, Routes, and Route tables to the
	// underlying Proxy, making them useful for controllers, validation tools, etc. which interact with kubernetes yaml.
	//
	// Some sample use cases:
	// * controllers, deployment pipelines, helm charts, etc. which wish to use extensions as a kind of opaque metadata.
	// * In the future, Gloo may support gRPC-based plugins which communicate with the Gloo translator out-of-process.
	// Opaque Extensions enables development of out-of-process plugins without requiring recompiling & redeploying Gloo's API.
	Extensions *Extensions `protobuf:"bytes,6,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// Defines route-specific tracing configuration.
	// See here for additional information on Envoy's tracing capabilities: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing.html
	// See here for additional information about configuring tracing with Gloo: https://gloo.solo.io/observability/tracing/
	Tracing *tracing.RouteTracingSettings `protobuf:"bytes,7,opt,name=tracing,proto3" json:"tracing,omitempty"`
	// Specifies traffic shadowing configuration for the route.
	// See here for additional information on Envoy's shadowing capabilities: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction-requestmirrorpolicy
	Shadowing *shadowing.RouteShadowing `protobuf:"bytes,8,opt,name=shadowing,proto3" json:"shadowing,omitempty"`
	// Append/Remove headers on Requests or Responses on this Route
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,9,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// For requests matched on this route, rewrite the Host header before forwarding upstream
	//
	// Types that are valid to be assigned to HostRewriteType:
	//	*RouteOptions_HostRewrite
	//	*RouteOptions_AutoHostRewrite
	HostRewriteType isRouteOptions_HostRewriteType `protobuf_oneof:"host_rewrite_type"`
	// Defines a CORS policy for the route
	// If a CORS policy is also defined on the route's virtual host, the policies are merged.
	Cors *cors.CorsPolicy `protobuf:"bytes,11,opt,name=cors,proto3" json:"cors,omitempty"`
	// For routes served by a hashing load balancer, this defines the input to the hash key
	// Gloo configures Envoy with the first available RouteActionHashConfig among the following ordered list of providers:
	// - route, upstream, virtual service
	LbHash *lbhash.RouteActionHashConfig `protobuf:"bytes,12,opt,name=lb_hash,json=lbHash,proto3" json:"lb_hash,omitempty"`
	// Route configuration for protocol upgrade requests.
	Upgrades []*protocol_upgrade.ProtocolUpgradeConfig `protobuf:"bytes,21,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	// Enterprise-only: Config for GlooE rate-limiting using simplified (gloo-specific) API
	RatelimitBasic *ratelimit.IngressRateLimit `protobuf:"bytes,13,opt,name=ratelimit_basic,json=ratelimitBasic,proto3" json:"ratelimit_basic,omitempty"`
	// Enterprise-only: Partial config for GlooE rate-limiting based on Envoy's rate-limit service;
	// supports Envoy's rate-limit service API. (reference here: https://github.com/lyft/ratelimit#configuration)
	// Configure rate-limit *actions* here, which define how request characteristics get translated into
	// descriptors used by the rate-limit service for rate-limiting. Configure rate-limit *descriptors* and
	// their associated limits on the Gloo settings
	Ratelimit *ratelimit.RateLimitRouteExtension `protobuf:"bytes,14,opt,name=ratelimit,proto3" json:"ratelimit,omitempty"`
	// Enterprise-only: Config for Web Application Firewall (WAF), supporting
	// the popular ModSecurity 3.0 ruleset
	Waf *waf.Settings `protobuf:"bytes,15,opt,name=waf,proto3" json:"waf,omitempty"`
	// Enterprise-only: Config for reading and verifying JWTs. Copy verifiable information from JWTs into other
	// headers to make routing decisions or combine with RBAC for fine-grained access control.
	Jwt *jwt.RouteExtension `protobuf:"bytes,16,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// Enterprise-only: Config for RBAC (currently only supports RBAC based on JWT claims)
	Rbac *rbac.ExtensionSettings `protobuf:"bytes,17,opt,name=rbac,proto3" json:"rbac,omitempty"`
	// Enterprise-only: Authentication configuration
	Extauth *v1.ExtAuthExtension `protobuf:"bytes,18,opt,name=extauth,proto3" json:"extauth,omitempty"`
	// Enterprise-only: Config for data loss prevention
	Dlp *dlp.Config `protobuf:"bytes,20,opt,name=dlp,proto3" json:"dlp,omitempty"`
	// BufferPerRoute can be used to set the maximum request size
	// that the filter will buffer before the connection
	// manager will stop buffering and return a 413 response.
	// Note: If you have not set a global config (at the gateway level), this
	// override will not do anything by itself.
	BufferPerRoute *v3.BufferPerRoute `protobuf:"bytes,22,opt,name=buffer_per_route,json=bufferPerRoute,proto3" json:"buffer_per_route,omitempty"`
	// Early transformations stage. These transformations run before most other options are processed.
	StagedTransformations *transformation.TransformationStages `protobuf:"bytes,23,opt,name=staged_transformations,json=stagedTransformations,proto3" json:"staged_transformations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *RouteOptions) Reset()         { *m = RouteOptions{} }
func (m *RouteOptions) String() string { return proto.CompactTextString(m) }
func (*RouteOptions) ProtoMessage()    {}
func (*RouteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{4}
}
func (m *RouteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteOptions.Unmarshal(m, b)
}
func (m *RouteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteOptions.Marshal(b, m, deterministic)
}
func (m *RouteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteOptions.Merge(m, src)
}
func (m *RouteOptions) XXX_Size() int {
	return xxx_messageInfo_RouteOptions.Size(m)
}
func (m *RouteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RouteOptions proto.InternalMessageInfo

type isRouteOptions_HostRewriteType interface {
	isRouteOptions_HostRewriteType()
	Equal(interface{}) bool
}

type RouteOptions_HostRewrite struct {
	HostRewrite string `protobuf:"bytes,10,opt,name=host_rewrite,json=hostRewrite,proto3,oneof" json:"host_rewrite,omitempty"`
}
type RouteOptions_AutoHostRewrite struct {
	AutoHostRewrite *types.BoolValue `protobuf:"bytes,19,opt,name=auto_host_rewrite,json=autoHostRewrite,proto3,oneof" json:"auto_host_rewrite,omitempty"`
}

func (*RouteOptions_HostRewrite) isRouteOptions_HostRewriteType()     {}
func (*RouteOptions_AutoHostRewrite) isRouteOptions_HostRewriteType() {}

func (m *RouteOptions) GetHostRewriteType() isRouteOptions_HostRewriteType {
	if m != nil {
		return m.HostRewriteType
	}
	return nil
}

func (m *RouteOptions) GetTransformations() *transformation.Transformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

func (m *RouteOptions) GetFaults() *faultinjection.RouteFaults {
	if m != nil {
		return m.Faults
	}
	return nil
}

func (m *RouteOptions) GetPrefixRewrite() *types.StringValue {
	if m != nil {
		return m.PrefixRewrite
	}
	return nil
}

func (m *RouteOptions) GetTimeout() *time.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *RouteOptions) GetRetries() *retries.RetryPolicy {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *RouteOptions) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *RouteOptions) GetTracing() *tracing.RouteTracingSettings {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *RouteOptions) GetShadowing() *shadowing.RouteShadowing {
	if m != nil {
		return m.Shadowing
	}
	return nil
}

func (m *RouteOptions) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *RouteOptions) GetHostRewrite() string {
	if x, ok := m.GetHostRewriteType().(*RouteOptions_HostRewrite); ok {
		return x.HostRewrite
	}
	return ""
}

func (m *RouteOptions) GetAutoHostRewrite() *types.BoolValue {
	if x, ok := m.GetHostRewriteType().(*RouteOptions_AutoHostRewrite); ok {
		return x.AutoHostRewrite
	}
	return nil
}

func (m *RouteOptions) GetCors() *cors.CorsPolicy {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *RouteOptions) GetLbHash() *lbhash.RouteActionHashConfig {
	if m != nil {
		return m.LbHash
	}
	return nil
}

func (m *RouteOptions) GetUpgrades() []*protocol_upgrade.ProtocolUpgradeConfig {
	if m != nil {
		return m.Upgrades
	}
	return nil
}

func (m *RouteOptions) GetRatelimitBasic() *ratelimit.IngressRateLimit {
	if m != nil {
		return m.RatelimitBasic
	}
	return nil
}

func (m *RouteOptions) GetRatelimit() *ratelimit.RateLimitRouteExtension {
	if m != nil {
		return m.Ratelimit
	}
	return nil
}

func (m *RouteOptions) GetWaf() *waf.Settings {
	if m != nil {
		return m.Waf
	}
	return nil
}

func (m *RouteOptions) GetJwt() *jwt.RouteExtension {
	if m != nil {
		return m.Jwt
	}
	return nil
}

func (m *RouteOptions) GetRbac() *rbac.ExtensionSettings {
	if m != nil {
		return m.Rbac
	}
	return nil
}

func (m *RouteOptions) GetExtauth() *v1.ExtAuthExtension {
	if m != nil {
		return m.Extauth
	}
	return nil
}

func (m *RouteOptions) GetDlp() *dlp.Config {
	if m != nil {
		return m.Dlp
	}
	return nil
}

func (m *RouteOptions) GetBufferPerRoute() *v3.BufferPerRoute {
	if m != nil {
		return m.BufferPerRoute
	}
	return nil
}

func (m *RouteOptions) GetStagedTransformations() *transformation.TransformationStages {
	if m != nil {
		return m.StagedTransformations
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RouteOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RouteOptions_HostRewrite)(nil),
		(*RouteOptions_AutoHostRewrite)(nil),
	}
}

// Configuration for Destinations that are tied to the UpstreamSpec or ServiceSpec on that destination
type DestinationSpec struct {
	// Note to developers: new DestinationSpecs must be added to this oneof field
	// to be usable by Gloo.
	//
	// Types that are valid to be assigned to DestinationType:
	//	*DestinationSpec_Aws
	//	*DestinationSpec_Azure
	//	*DestinationSpec_Rest
	//	*DestinationSpec_Grpc
	DestinationType      isDestinationSpec_DestinationType `protobuf_oneof:"destination_type"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *DestinationSpec) Reset()         { *m = DestinationSpec{} }
func (m *DestinationSpec) String() string { return proto.CompactTextString(m) }
func (*DestinationSpec) ProtoMessage()    {}
func (*DestinationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{5}
}
func (m *DestinationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestinationSpec.Unmarshal(m, b)
}
func (m *DestinationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestinationSpec.Marshal(b, m, deterministic)
}
func (m *DestinationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestinationSpec.Merge(m, src)
}
func (m *DestinationSpec) XXX_Size() int {
	return xxx_messageInfo_DestinationSpec.Size(m)
}
func (m *DestinationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_DestinationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_DestinationSpec proto.InternalMessageInfo

type isDestinationSpec_DestinationType interface {
	isDestinationSpec_DestinationType()
	Equal(interface{}) bool
}

type DestinationSpec_Aws struct {
	Aws *aws.DestinationSpec `protobuf:"bytes,1,opt,name=aws,proto3,oneof" json:"aws,omitempty"`
}
type DestinationSpec_Azure struct {
	Azure *azure.DestinationSpec `protobuf:"bytes,2,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
}
type DestinationSpec_Rest struct {
	Rest *rest.DestinationSpec `protobuf:"bytes,3,opt,name=rest,proto3,oneof" json:"rest,omitempty"`
}
type DestinationSpec_Grpc struct {
	Grpc *grpc.DestinationSpec `protobuf:"bytes,4,opt,name=grpc,proto3,oneof" json:"grpc,omitempty"`
}

func (*DestinationSpec_Aws) isDestinationSpec_DestinationType()   {}
func (*DestinationSpec_Azure) isDestinationSpec_DestinationType() {}
func (*DestinationSpec_Rest) isDestinationSpec_DestinationType()  {}
func (*DestinationSpec_Grpc) isDestinationSpec_DestinationType()  {}

func (m *DestinationSpec) GetDestinationType() isDestinationSpec_DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return nil
}

func (m *DestinationSpec) GetAws() *aws.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *DestinationSpec) GetAzure() *azure.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Azure); ok {
		return x.Azure
	}
	return nil
}

func (m *DestinationSpec) GetRest() *rest.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Rest); ok {
		return x.Rest
	}
	return nil
}

func (m *DestinationSpec) GetGrpc() *grpc.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Grpc); ok {
		return x.Grpc
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DestinationSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DestinationSpec_Aws)(nil),
		(*DestinationSpec_Azure)(nil),
		(*DestinationSpec_Rest)(nil),
		(*DestinationSpec_Grpc)(nil),
	}
}

// Optional, feature-specific configuration that is applied when a specific weighted destination
// is selected for routing.
type WeightedDestinationOptions struct {
	// Append/Remove headers on Requests or Responses to/from this Weighted Destination
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,1,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Transformations to apply. Note: this field is superceded by `staged_transformations`.
	// If `staged_transformations.XXX` is set, this field will be ignored.
	Transformations *transformation.Transformations `protobuf:"bytes,2,opt,name=transformations,proto3" json:"transformations,omitempty"`
	// Extensions will be passed along from Listeners, Gateways, VirtualServices, Routes, and Route tables to the
	// underlying Proxy, making them useful for controllers, validation tools, etc. which interact with kubernetes yaml.
	//
	// Some sample use cases:
	// * controllers, deployment pipelines, helm charts, etc. which wish to use extensions as a kind of opaque metadata.
	// * In the future, Gloo may support gRPC-based plugins which communicate with the Gloo translator out-of-process.
	// Opaque Extensions enables development of out-of-process plugins without requiring recompiling & redeploying Gloo's API.
	Extensions *Extensions `protobuf:"bytes,3,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// Enterprise-only: Authentication configuration
	Extauth *v1.ExtAuthExtension `protobuf:"bytes,4,opt,name=extauth,proto3" json:"extauth,omitempty"`
	// BufferPerRoute can be used to set the maximum request size
	// that the filter will buffer before the connection
	// manager will stop buffering and return a 413 response.
	// Note: If you have not set a global config (at the gateway level), this
	// override will not do anything by itself.
	BufferPerRoute *v3.BufferPerRoute `protobuf:"bytes,5,opt,name=buffer_per_route,json=bufferPerRoute,proto3" json:"buffer_per_route,omitempty"`
	// Early transformations stage. These transformations run before most other options are processed.
	// If the XXX field is set in here, the `transformations` field is ignored.
	StagedTransformations *transformation.TransformationStages `protobuf:"bytes,6,opt,name=staged_transformations,json=stagedTransformations,proto3" json:"staged_transformations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *WeightedDestinationOptions) Reset()         { *m = WeightedDestinationOptions{} }
func (m *WeightedDestinationOptions) String() string { return proto.CompactTextString(m) }
func (*WeightedDestinationOptions) ProtoMessage()    {}
func (*WeightedDestinationOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_94dcee4f7557dfdc, []int{6}
}
func (m *WeightedDestinationOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightedDestinationOptions.Unmarshal(m, b)
}
func (m *WeightedDestinationOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightedDestinationOptions.Marshal(b, m, deterministic)
}
func (m *WeightedDestinationOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedDestinationOptions.Merge(m, src)
}
func (m *WeightedDestinationOptions) XXX_Size() int {
	return xxx_messageInfo_WeightedDestinationOptions.Size(m)
}
func (m *WeightedDestinationOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedDestinationOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedDestinationOptions proto.InternalMessageInfo

func (m *WeightedDestinationOptions) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *WeightedDestinationOptions) GetTransformations() *transformation.Transformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

func (m *WeightedDestinationOptions) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *WeightedDestinationOptions) GetExtauth() *v1.ExtAuthExtension {
	if m != nil {
		return m.Extauth
	}
	return nil
}

func (m *WeightedDestinationOptions) GetBufferPerRoute() *v3.BufferPerRoute {
	if m != nil {
		return m.BufferPerRoute
	}
	return nil
}

func (m *WeightedDestinationOptions) GetStagedTransformations() *transformation.TransformationStages {
	if m != nil {
		return m.StagedTransformations
	}
	return nil
}

func init() {
	proto.RegisterType((*ListenerOptions)(nil), "gloo.solo.io.ListenerOptions")
	proto.RegisterType((*HttpListenerOptions)(nil), "gloo.solo.io.HttpListenerOptions")
	proto.RegisterType((*TcpListenerOptions)(nil), "gloo.solo.io.TcpListenerOptions")
	proto.RegisterType((*VirtualHostOptions)(nil), "gloo.solo.io.VirtualHostOptions")
	proto.RegisterType((*RouteOptions)(nil), "gloo.solo.io.RouteOptions")
	proto.RegisterType((*DestinationSpec)(nil), "gloo.solo.io.DestinationSpec")
	proto.RegisterType((*WeightedDestinationOptions)(nil), "gloo.solo.io.WeightedDestinationOptions")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/options.proto", fileDescriptor_94dcee4f7557dfdc)
}

var fileDescriptor_94dcee4f7557dfdc = []byte{
	// 1823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0xdb, 0x72, 0xd3, 0xce,
	0x19, 0xc7, 0x89, 0x13, 0x27, 0x9b, 0x23, 0x1b, 0xa0, 0x6e, 0x06, 0x68, 0x48, 0xa7, 0x25, 0xd0,
	0xb2, 0x06, 0x87, 0x36, 0x24, 0xd0, 0xa1, 0x49, 0x38, 0x98, 0x21, 0x4c, 0x33, 0x72, 0x38, 0xb4,
	0x9d, 0xa9, 0x66, 0x2d, 0xaf, 0x25, 0x81, 0xa2, 0xd5, 0xec, 0xae, 0xec, 0x84, 0xab, 0x5e, 0xf6,
	0x11, 0xda, 0x37, 0xe8, 0x4d, 0xaf, 0x7a, 0xd3, 0x37, 0xe8, 0x63, 0x74, 0xa6, 0xef, 0xd0, 0xdb,
	0xce, 0x7f, 0xf6, 0x20, 0xf9, 0x10, 0x19, 0xcb, 0x21, 0x70, 0x21, 0x59, 0x2b, 0x7d, 0xbf, 0xdf,
	0xae, 0x76, 0xbf, 0xef, 0xf7, 0x7d, 0x5a, 0x83, 0x1d, 0xd7, 0x17, 0x5e, 0xdc, 0x40, 0x0e, 0x3d,
	0xae, 0x70, 0x1a, 0xd0, 0x7b, 0x3e, 0xad, 0xb8, 0x01, 0xa5, 0x95, 0x88, 0xd1, 0x8f, 0xc4, 0x11,
	0x5c, 0xb7, 0x70, 0xe4, 0x57, 0xda, 0x0f, 0x2a, 0x34, 0x12, 0x3e, 0x0d, 0x39, 0x8a, 0x18, 0x15,
	0x14, 0xce, 0xcb, 0x47, 0x48, 0xa2, 0x90, 0x4f, 0x57, 0xaf, 0xbb, 0x94, 0xba, 0x01, 0xa9, 0xa8,
	0x67, 0x8d, 0xb8, 0x55, 0xe1, 0x82, 0xc5, 0x8e, 0xd0, 0xb6, 0xab, 0x57, 0x5c, 0xea, 0x52, 0x75,
	0x59, 0x91, 0x57, 0xe6, 0x2e, 0x24, 0x27, 0x42, 0xdf, 0x24, 0x27, 0x89, 0xe5, 0xdd, 0xe1, 0xdd,
	0x93, 0x13, 0x41, 0x42, 0xde, 0x1d, 0xc1, 0xea, 0x83, 0x91, 0x43, 0xad, 0x38, 0x94, 0xe9, 0x53,
	0x7e, 0x08, 0x23, 0x5c, 0xa8, 0x53, 0x7e, 0x88, 0xcb, 0x22, 0x47, 0x9d, 0x0c, 0x64, 0xf4, 0x1c,
	0x56, 0x70, 0xa0, 0x0e, 0x03, 0xd8, 0xce, 0xd7, 0x87, 0xdd, 0x21, 0x8d, 0xf4, 0x22, 0x7f, 0x5f,
	0x9e, 0x73, 0x2c, 0x0f, 0x03, 0xf8, 0xd5, 0x68, 0x40, 0xd0, 0xf0, 0x30, 0xf7, 0xcc, 0x8f, 0x81,
	0x3d, 0x1e, 0x0d, 0xe3, 0x1e, 0x6e, 0xd2, 0x8e, 0x1f, 0xba, 0xdd, 0xab, 0xfc, 0x83, 0x14, 0x4e,
	0x24, 0x0f, 0x03, 0xd8, 0xca, 0x01, 0x60, 0xd8, 0x91, 0x7d, 0x99, 0xdf, 0xfc, 0x40, 0x46, 0x04,
	0xf3, 0x49, 0xfa, 0x6b, 0x80, 0x9b, 0x39, 0xde, 0x4f, 0x60, 0x61, 0xce, 0x06, 0xf4, 0x64, 0x34,
	0xa8, 0x85, 0xe3, 0x40, 0xf8, 0xa1, 0x34, 0xf0, 0x69, 0xa8, 0x9b, 0xf9, 0xc7, 0xea, 0x11, 0xdc,
	0x24, 0x2c, 0xfd, 0x1d, 0xc3, 0xbf, 0x3a, 0xea, 0xc8, 0xef, 0xc3, 0x1d, 0xcc, 0x8f, 0xd5, 0x29,
	0xff, 0x7c, 0xe0, 0xcf, 0x31, 0x23, 0xfa, 0x6c, 0x40, 0x4f, 0x73, 0xbd, 0x51, 0x20, 0x3c, 0xc7,
	0x23, 0xce, 0xa7, 0xde, 0x6b, 0x43, 0xf0, 0x6a, 0x34, 0x81, 0x32, 0x74, 0x68, 0x60, 0xc7, 0x91,
	0xcb, 0x70, 0x93, 0x9c, 0xb9, 0x61, 0xa8, 0x9e, 0xe7, 0x72, 0xa1, 0x90, 0xb7, 0x28, 0x3b, 0xc6,
	0x6a, 0x6d, 0xfa, 0x9b, 0x86, 0xe6, 0x68, 0x08, 0x8d, 0x54, 0x23, 0x16, 0xe2, 0xa0, 0x42, 0xc2,
	0x36, 0x3d, 0xed, 0x11, 0xa7, 0x5c, 0xac, 0x87, 0x63, 0xb3, 0x46, 0x8c, 0x9e, 0x9c, 0x06, 0x58,
	0x90, 0xd0, 0x39, 0xed, 0x6b, 0x9c, 0x7b, 0x9c, 0x2d, 0x3f, 0x10, 0xca, 0xb7, 0x84, 0x88, 0x2a,
	0x8d, 0xb8, 0xd5, 0x22, 0xac, 0xd2, 0xde, 0x34, 0x57, 0x86, 0xf5, 0x75, 0x3e, 0x56, 0x87, 0x86,
	0x2d, 0xdf, 0x35, 0x8c, 0x9a, 0xd0, 0xfd, 0xec, 0x47, 0x95, 0x76, 0x55, 0xfd, 0x8e, 0x5e, 0x11,
	0x12, 0x0a, 0xc2, 0x22, 0xe6, 0x73, 0x92, 0x2e, 0x0e, 0x39, 0x11, 0x38, 0x16, 0x9e, 0x51, 0x7e,
	0x79, 0x69, 0x68, 0x76, 0xc6, 0xa2, 0xf9, 0xd8, 0x11, 0xf2, 0x30, 0xd8, 0x17, 0x63, 0x61, 0x19,
	0x16, 0x24, 0xf0, 0x8f, 0x7d, 0xd1, 0xbd, 0x1a, 0x1d, 0xf8, 0x59, 0x3c, 0x0d, 0xec, 0xa8, 0xd3,
	0xb9, 0xde, 0xa0, 0x83, 0x5b, 0xf2, 0x38, 0x17, 0xb6, 0x19, 0x44, 0xf2, 0x30, 0xd8, 0x9b, 0x83,
	0x49, 0xba, 0x19, 0xb3, 0x5e, 0xaf, 0x3c, 0xf3, 0xbc, 0xc3, 0x70, 0x14, 0xa5, 0xba, 0xb3, 0xfe,
	0xb7, 0x09, 0xb0, 0x74, 0xe0, 0x73, 0x41, 0x42, 0xc2, 0x7e, 0xa7, 0x7b, 0x80, 0x4d, 0x70, 0x0d,
	0x3b, 0x0e, 0xe1, 0xdc, 0x0e, 0xa8, 0xeb, 0xfa, 0xa1, 0x6b, 0x73, 0xc2, 0xda, 0xbe, 0x43, 0xca,
	0x85, 0xb5, 0xc2, 0xc6, 0x5c, 0x15, 0x21, 0x99, 0xe6, 0x92, 0xd2, 0xa1, 0xb7, 0x66, 0x40, 0xbb,
	0x0a, 0x77, 0xa0, 0x61, 0x75, 0x8d, 0xb2, 0xae, 0xe0, 0x8c, 0xbb, 0xf0, 0x11, 0x00, 0x5d, 0xcf,
	0x2d, 0x4f, 0x28, 0xe6, 0x72, 0x3f, 0xdb, 0xf3, 0xf4, 0xb9, 0xd5, 0x63, 0x0b, 0x5b, 0xe0, 0x56,
	0x44, 0x98, 0xed, 0xd0, 0x30, 0xd4, 0x12, 0x6c, 0x6b, 0x07, 0xb7, 0xd5, 0x72, 0xda, 0x8d, 0x53,
	0x41, 0x78, 0x79, 0x52, 0x11, 0x5e, 0x47, 0xfa, 0xfd, 0x51, 0xf2, 0xfe, 0xe8, 0xed, 0xab, 0x50,
	0x6c, 0x56, 0xdf, 0xe1, 0x20, 0x26, 0xd6, 0x8d, 0x88, 0xb0, 0xfd, 0x94, 0x65, 0x4f, 0x91, 0x1c,
	0x48, 0x8e, 0x3d, 0x49, 0xb1, 0xfe, 0x97, 0x12, 0x58, 0xa9, 0x09, 0x11, 0x0d, 0xce, 0xcf, 0x2e,
	0x98, 0x49, 0x32, 0xb6, 0x99, 0x91, 0x9f, 0xa3, 0x34, 0x85, 0x67, 0x4e, 0xcb, 0x4b, 0x16, 0x39,
	0xef, 0x49, 0xc3, 0x2a, 0xb9, 0xfa, 0x02, 0xfe, 0xb9, 0x00, 0xd6, 0x64, 0x4c, 0xf5, 0xbe, 0xc4,
	0x31, 0x0e, 0xb1, 0x4b, 0x98, 0xcd, 0x89, 0x10, 0x7e, 0xe8, 0x26, 0x73, 0xb2, 0x85, 0x64, 0xa2,
	0xcf, 0xa4, 0x95, 0x83, 0xeb, 0x8e, 0xff, 0x8d, 0xc6, 0xd7, 0x0d, 0xdc, 0xba, 0xe1, 0x7d, 0xe9,
	0x31, 0x3c, 0x04, 0xf3, 0x5a, 0xac, 0x6d, 0xa5, 0xd6, 0xe5, 0xa2, 0xea, 0xed, 0x1e, 0xea, 0x55,
	0xf0, 0xec, 0x5e, 0x95, 0xc1, 0xbe, 0x34, 0xb0, 0xe6, 0xbc, 0x6e, 0x63, 0x60, 0x45, 0x27, 0xc7,
	0x58, 0xd1, 0x87, 0x60, 0xb2, 0x83, 0x5b, 0xe5, 0x29, 0x05, 0x59, 0x47, 0x32, 0x34, 0x32, 0xbb,
	0x4e, 0xdf, 0x4d, 0x9a, 0xc3, 0x47, 0x60, 0xb2, 0x19, 0x44, 0xe5, 0x69, 0xb3, 0x04, 0x32, 0x28,
	0x32, 0x51, 0x2f, 0x94, 0x86, 0xed, 0x2b, 0x41, 0xb3, 0x24, 0x04, 0x3e, 0x06, 0x45, 0x99, 0x17,
	0xcb, 0x25, 0x05, 0xbd, 0x8d, 0x54, 0x92, 0xcc, 0xc4, 0x1e, 0x06, 0xb1, 0xeb, 0x87, 0x75, 0x1a,
	0x33, 0x87, 0x58, 0x0a, 0x04, 0x1f, 0x83, 0x92, 0x51, 0xaf, 0x32, 0x50, 0xf8, 0x5b, 0xa8, 0x1b,
	0xa6, 0x43, 0xc6, 0x9b, 0x20, 0x60, 0x1d, 0x2c, 0xa7, 0xc2, 0xa3, 0xc2, 0x8a, 0xb0, 0xf2, 0x9c,
	0x62, 0xd9, 0x40, 0x5d, 0x45, 0xfa, 0xf2, 0xcb, 0x2f, 0xa5, 0x86, 0x75, 0x45, 0x00, 0x77, 0x40,
	0x51, 0x6a, 0x72, 0x79, 0xc6, 0xcc, 0x84, 0x52, 0x70, 0xa4, 0x15, 0x1c, 0x69, 0x05, 0x47, 0xd2,
	0x19, 0x90, 0x52, 0xee, 0x76, 0x15, 0xbd, 0xfc, 0xec, 0x47, 0x96, 0xc2, 0xc0, 0x3f, 0x82, 0x05,
	0x95, 0x7a, 0x6c, 0x93, 0x7b, 0xca, 0xb3, 0x8a, 0xe4, 0xd7, 0xc3, 0x49, 0xfa, 0x32, 0x55, 0xbb,
	0x8a, 0x0e, 0x65, 0xfb, 0x40, 0xb7, 0xad, 0xf9, 0xa8, 0xa7, 0x05, 0x5f, 0x82, 0x69, 0x1d, 0x9a,
	0xe5, 0x79, 0xc5, 0x5a, 0x31, 0xac, 0x3d, 0x75, 0xbf, 0x49, 0x59, 0x9a, 0xda, 0x24, 0xaa, 0xf6,
	0x26, 0xd2, 0xc1, 0x68, 0x19, 0xf8, 0x7a, 0x08, 0xe0, 0x91, 0x73, 0x26, 0x10, 0x3f, 0x00, 0x28,
	0x9c, 0xc8, 0xd6, 0xe3, 0x4f, 0xc3, 0x46, 0x3b, 0xde, 0x5d, 0x24, 0x4b, 0xcf, 0xcc, 0x89, 0x3c,
	0x72, 0x22, 0x35, 0xe6, 0x74, 0x42, 0x97, 0xc5, 0xc0, 0x9d, 0xf5, 0xff, 0xcf, 0x00, 0xf8, 0xce,
	0x67, 0x22, 0xc6, 0x41, 0x8d, 0x72, 0x91, 0x74, 0xd8, 0xef, 0xe1, 0x85, 0x31, 0x3c, 0x7c, 0x1f,
	0x94, 0x4c, 0x71, 0x6a, 0xbc, 0xfc, 0x0e, 0x4a, 0x8a, 0xd5, 0xcc, 0x31, 0x5a, 0x44, 0xb0, 0xd3,
	0x43, 0x1a, 0xf8, 0xce, 0xa9, 0x95, 0x20, 0xe1, 0x16, 0x98, 0x52, 0xa5, 0x6a, 0xea, 0x77, 0xba,
	0x70, 0xcd, 0xf6, 0x16, 0xf9, 0xc8, 0xd2, 0xf6, 0x10, 0x83, 0x15, 0x5d, 0x6e, 0x4a, 0x91, 0xf1,
	0xa3, 0x38, 0x50, 0x29, 0xc2, 0x08, 0xcc, 0x7d, 0x94, 0x94, 0xa2, 0xc3, 0xc2, 0xbd, 0x49, 0xd8,
	0x9b, 0x1e, 0x9c, 0x05, 0xbd, 0x33, 0xf7, 0xe0, 0x36, 0x28, 0xca, 0x8f, 0x32, 0x33, 0xfb, 0x3f,
	0x43, 0xea, 0x0b, 0x2d, 0x93, 0x70, 0x9f, 0x32, 0x6e, 0xde, 0x4c, 0x41, 0xe0, 0x9f, 0xc0, 0x52,
	0x7f, 0x45, 0xc5, 0x8d, 0x18, 0x3d, 0x44, 0x03, 0x95, 0x56, 0xf6, 0x72, 0xf6, 0x63, 0xad, 0x41,
	0x32, 0xf8, 0x7b, 0xd0, 0x8d, 0x18, 0xbb, 0x81, 0xb9, 0xef, 0x18, 0xcd, 0xb8, 0x3f, 0x2a, 0xe4,
	0x5e, 0x85, 0x2e, 0x23, 0x9c, 0x5b, 0x58, 0x10, 0x95, 0x17, 0xac, 0xc5, 0x14, 0xb0, 0x27, 0x79,
	0xe0, 0x5b, 0x30, 0x9b, 0xde, 0x31, 0x6a, 0xb2, 0x35, 0x8a, 0x34, 0x65, 0x7b, 0xe7, 0x51, 0x2e,
	0x52, 0x7f, 0xb1, 0xba, 0x4c, 0x89, 0x1e, 0xce, 0x8c, 0xa7, 0x87, 0x3b, 0x60, 0xf2, 0x63, 0x47,
	0x98, 0x00, 0xde, 0x40, 0xb2, 0x44, 0xca, 0x44, 0x0d, 0xf4, 0x2b, 0x41, 0xf0, 0xb7, 0xa0, 0x28,
	0xab, 0x19, 0xa3, 0x45, 0xbf, 0x44, 0xaa, 0xb4, 0xc9, 0x44, 0xa7, 0xc0, 0xb4, 0x73, 0x85, 0x94,
	0x1e, 0x9e, 0xc8, 0xe2, 0xbc, 0xf1, 0xf0, 0x61, 0xb2, 0xf8, 0xfc, 0x44, 0xec, 0xc6, 0xc2, 0xeb,
	0x0e, 0x21, 0x95, 0xc7, 0xaa, 0x96, 0xf4, 0x05, 0x45, 0xb0, 0x36, 0x5c, 0xd2, 0x7b, 0xc5, 0x1c,
	0x83, 0x65, 0x93, 0xff, 0x65, 0x55, 0xc0, 0x68, 0x2c, 0x48, 0x79, 0xd1, 0x2c, 0xc5, 0x78, 0x72,
	0x73, 0x48, 0x98, 0x25, 0xe1, 0xd6, 0x62, 0xa3, 0xaf, 0x0d, 0x23, 0x70, 0x8d, 0x0b, 0xec, 0x92,
	0xa6, 0x3d, 0xe8, 0xa8, 0x4b, 0xaa, 0xa3, 0xed, 0x73, 0x38, 0x6a, 0x5d, 0x12, 0x72, 0xeb, 0xaa,
	0x26, 0x1e, 0x70, 0xe2, 0xf5, 0x7f, 0x2f, 0x80, 0x79, 0xd5, 0x77, 0x22, 0x3d, 0x19, 0x41, 0x52,
	0xb8, 0xc8, 0x20, 0x79, 0x0a, 0xa6, 0xd5, 0x87, 0x6c, 0x52, 0x76, 0xdc, 0x46, 0xfa, 0xbb, 0x36,
	0xdb, 0x85, 0xe5, 0xc8, 0x5e, 0x28, 0x73, 0xcb, 0xc0, 0xe0, 0x3e, 0x58, 0x8c, 0x18, 0x69, 0xf9,
	0x27, 0x36, 0x23, 0x1d, 0xe6, 0x0b, 0x32, 0xb4, 0x04, 0xab, 0x0b, 0xe6, 0x87, 0xae, 0x2e, 0xc1,
	0x16, 0x34, 0xc6, 0xd2, 0x10, 0xb8, 0x0d, 0x4a, 0xc2, 0x3f, 0x26, 0x34, 0x16, 0x46, 0x02, 0x7e,
	0x7c, 0x06, 0xfd, 0xcc, 0x14, 0xb8, 0x7b, 0xc5, 0xbf, 0xfe, 0xe7, 0x27, 0x05, 0x2b, 0xb1, 0xbf,
	0x18, 0x85, 0xed, 0x17, 0xf8, 0xe9, 0x31, 0x04, 0xfe, 0x00, 0x94, 0xcc, 0xb6, 0x85, 0xd1, 0x81,
	0x2a, 0x4a, 0xb6, 0x31, 0x86, 0x4f, 0xe1, 0x91, 0xb6, 0xe8, 0x96, 0x09, 0x06, 0x02, 0x0f, 0xc0,
	0x6c, 0xba, 0xe1, 0x62, 0x64, 0x00, 0xa1, 0xee, 0x16, 0xcc, 0x70, 0xc6, 0x7a, 0x62, 0x63, 0x75,
	0x09, 0x86, 0xc9, 0xff, 0xec, 0x05, 0xca, 0xff, 0x4f, 0xc1, 0xbc, 0x54, 0x95, 0x74, 0xed, 0x65,
	0x86, 0x9a, 0xad, 0x5d, 0xb2, 0xe6, 0xe4, 0xdd, 0x64, 0x75, 0x6b, 0xe0, 0x32, 0x8e, 0x05, 0xb5,
	0xfb, 0x2c, 0x57, 0xd4, 0x28, 0x56, 0xcf, 0xac, 0xf3, 0x1e, 0xa5, 0x81, 0xf2, 0x91, 0xda, 0x25,
	0x6b, 0x49, 0xc2, 0x6a, 0x3d, 0x4c, 0x49, 0xb6, 0x99, 0x1b, 0x3f, 0xdb, 0xbc, 0x06, 0xa5, 0xa0,
	0x61, 0x7b, 0x98, 0x27, 0x3a, 0x55, 0x45, 0x66, 0x57, 0x6c, 0xf8, 0xac, 0xee, 0xaa, 0x0a, 0xba,
	0x86, 0xb9, 0x67, 0x84, 0x67, 0x3a, 0x68, 0xc8, 0x16, 0xfc, 0x00, 0x66, 0xcc, 0x16, 0x05, 0x2f,
	0x5f, 0x5d, 0x9b, 0xdc, 0x98, 0xab, 0x3e, 0x41, 0x67, 0x36, 0x2f, 0xb2, 0x0b, 0x4b, 0x63, 0xf5,
	0x56, 0x1b, 0x19, 0xde, 0x94, 0x2d, 0x2b, 0x69, 0x2d, 0x7c, 0x8b, 0xa4, 0xb5, 0x38, 0x66, 0xd2,
	0x52, 0xf3, 0xf1, 0xa5, 0xa4, 0xb5, 0x74, 0xae, 0xa4, 0xb5, 0x3c, 0x2a, 0x69, 0x0d, 0xf4, 0xdb,
	0x97, 0xb4, 0x2e, 0x5f, 0x44, 0xd2, 0x82, 0x5f, 0x9b, 0xb4, 0xae, 0x7c, 0x6d, 0xd2, 0xba, 0xf6,
	0xbd, 0x92, 0xd6, 0x8f, 0xbe, 0x4d, 0xd2, 0xda, 0x5b, 0x01, 0x97, 0x7b, 0x43, 0xdb, 0x16, 0xa7,
	0x11, 0x59, 0xff, 0xc7, 0x04, 0x58, 0x7a, 0x46, 0xb8, 0xf0, 0x43, 0xcd, 0x10, 0x11, 0x07, 0xfe,
	0x06, 0x4c, 0xe2, 0x4e, 0x92, 0xc0, 0xee, 0x20, 0xdc, 0x19, 0x12, 0xbc, 0x03, 0xb8, 0xda, 0x25,
	0x4b, 0xe2, 0xe0, 0x3e, 0x98, 0x52, 0x5b, 0x94, 0x26, 0x55, 0xfd, 0x02, 0xe9, 0x0d, 0xcb, 0x9c,
	0x14, 0x1a, 0xab, 0x9c, 0x87, 0x70, 0x91, 0x7e, 0x2e, 0xa8, 0xff, 0x07, 0x72, 0x52, 0x28, 0xa4,
	0x64, 0x90, 0xdf, 0xf3, 0x26, 0x53, 0xdd, 0x55, 0x7b, 0x00, 0xb9, 0x19, 0xa4, 0xf1, 0x1e, 0x04,
	0xcb, 0xcd, 0xee, 0x23, 0x3d, 0x5f, 0xff, 0x2c, 0x82, 0xd5, 0xf7, 0xc4, 0x77, 0x3d, 0x41, 0x9a,
	0x3d, 0xb8, 0xa4, 0x0e, 0x18, 0xa2, 0xe5, 0x85, 0x0b, 0xd4, 0xf2, 0x8c, 0x52, 0x63, 0xe2, 0x22,
	0x4b, 0x8d, 0xf3, 0xef, 0x13, 0xf4, 0x84, 0x6b, 0xf1, 0xdc, 0xe1, 0x9a, 0x15, 0x7a, 0x53, 0xdf,
	0x2b, 0xf4, 0xa6, 0xbf, 0x51, 0xe8, 0xed, 0xfc, 0xeb, 0x7f, 0xc5, 0xc2, 0xdf, 0xff, 0x7b, 0xb3,
	0xf0, 0x87, 0xfb, 0xf9, 0xfe, 0x00, 0x8c, 0x3e, 0xb9, 0x66, 0x93, 0xb1, 0x31, 0xad, 0x32, 0xd6,
	0xe6, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x98, 0x4b, 0x39, 0x3b, 0x1c, 0x00, 0x00,
}

func (this *ListenerOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListenerOptions)
	if !ok {
		that2, ok := that.(ListenerOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AccessLoggingService.Equal(that1.AccessLoggingService) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.PerConnectionBufferLimitBytes.Equal(that1.PerConnectionBufferLimitBytes) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HttpListenerOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HttpListenerOptions)
	if !ok {
		that2, ok := that.(HttpListenerOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.GrpcWeb.Equal(that1.GrpcWeb) {
		return false
	}
	if !this.HttpConnectionManagerSettings.Equal(that1.HttpConnectionManagerSettings) {
		return false
	}
	if !this.HealthCheck.Equal(that1.HealthCheck) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Waf.Equal(that1.Waf) {
		return false
	}
	if !this.Dlp.Equal(that1.Dlp) {
		return false
	}
	if !this.Wasm.Equal(that1.Wasm) {
		return false
	}
	if !this.Extauth.Equal(that1.Extauth) {
		return false
	}
	if !this.RatelimitServer.Equal(that1.RatelimitServer) {
		return false
	}
	if !this.Gzip.Equal(that1.Gzip) {
		return false
	}
	if !this.ProxyLatency.Equal(that1.ProxyLatency) {
		return false
	}
	if !this.Buffer.Equal(that1.Buffer) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TcpListenerOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TcpListenerOptions)
	if !ok {
		that2, ok := that.(TcpListenerOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TcpProxySettings.Equal(that1.TcpProxySettings) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *VirtualHostOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VirtualHostOptions)
	if !ok {
		that2, ok := that.(VirtualHostOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.Stats.Equal(that1.Stats) {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.Cors.Equal(that1.Cors) {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !this.RatelimitBasic.Equal(that1.RatelimitBasic) {
		return false
	}
	if !this.Ratelimit.Equal(that1.Ratelimit) {
		return false
	}
	if !this.Waf.Equal(that1.Waf) {
		return false
	}
	if !this.Jwt.Equal(that1.Jwt) {
		return false
	}
	if !this.Rbac.Equal(that1.Rbac) {
		return false
	}
	if !this.Extauth.Equal(that1.Extauth) {
		return false
	}
	if !this.Dlp.Equal(that1.Dlp) {
		return false
	}
	if !this.BufferPerRoute.Equal(that1.BufferPerRoute) {
		return false
	}
	if !this.StagedTransformations.Equal(that1.StagedTransformations) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RouteOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RouteOptions)
	if !ok {
		that2, ok := that.(RouteOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !this.Faults.Equal(that1.Faults) {
		return false
	}
	if !this.PrefixRewrite.Equal(that1.PrefixRewrite) {
		return false
	}
	if this.Timeout != nil && that1.Timeout != nil {
		if *this.Timeout != *that1.Timeout {
			return false
		}
	} else if this.Timeout != nil {
		return false
	} else if that1.Timeout != nil {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Tracing.Equal(that1.Tracing) {
		return false
	}
	if !this.Shadowing.Equal(that1.Shadowing) {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if that1.HostRewriteType == nil {
		if this.HostRewriteType != nil {
			return false
		}
	} else if this.HostRewriteType == nil {
		return false
	} else if !this.HostRewriteType.Equal(that1.HostRewriteType) {
		return false
	}
	if !this.Cors.Equal(that1.Cors) {
		return false
	}
	if !this.LbHash.Equal(that1.LbHash) {
		return false
	}
	if len(this.Upgrades) != len(that1.Upgrades) {
		return false
	}
	for i := range this.Upgrades {
		if !this.Upgrades[i].Equal(that1.Upgrades[i]) {
			return false
		}
	}
	if !this.RatelimitBasic.Equal(that1.RatelimitBasic) {
		return false
	}
	if !this.Ratelimit.Equal(that1.Ratelimit) {
		return false
	}
	if !this.Waf.Equal(that1.Waf) {
		return false
	}
	if !this.Jwt.Equal(that1.Jwt) {
		return false
	}
	if !this.Rbac.Equal(that1.Rbac) {
		return false
	}
	if !this.Extauth.Equal(that1.Extauth) {
		return false
	}
	if !this.Dlp.Equal(that1.Dlp) {
		return false
	}
	if !this.BufferPerRoute.Equal(that1.BufferPerRoute) {
		return false
	}
	if !this.StagedTransformations.Equal(that1.StagedTransformations) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RouteOptions_HostRewrite) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RouteOptions_HostRewrite)
	if !ok {
		that2, ok := that.(RouteOptions_HostRewrite)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.HostRewrite != that1.HostRewrite {
		return false
	}
	return true
}
func (this *RouteOptions_AutoHostRewrite) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RouteOptions_AutoHostRewrite)
	if !ok {
		that2, ok := that.(RouteOptions_AutoHostRewrite)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AutoHostRewrite.Equal(that1.AutoHostRewrite) {
		return false
	}
	return true
}
func (this *DestinationSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec)
	if !ok {
		that2, ok := that.(DestinationSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.DestinationType == nil {
		if this.DestinationType != nil {
			return false
		}
	} else if this.DestinationType == nil {
		return false
	} else if !this.DestinationType.Equal(that1.DestinationType) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DestinationSpec_Aws) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Aws)
	if !ok {
		that2, ok := that.(DestinationSpec_Aws)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Aws.Equal(that1.Aws) {
		return false
	}
	return true
}
func (this *DestinationSpec_Azure) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Azure)
	if !ok {
		that2, ok := that.(DestinationSpec_Azure)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Azure.Equal(that1.Azure) {
		return false
	}
	return true
}
func (this *DestinationSpec_Rest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Rest)
	if !ok {
		that2, ok := that.(DestinationSpec_Rest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Rest.Equal(that1.Rest) {
		return false
	}
	return true
}
func (this *DestinationSpec_Grpc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Grpc)
	if !ok {
		that2, ok := that.(DestinationSpec_Grpc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Grpc.Equal(that1.Grpc) {
		return false
	}
	return true
}
func (this *WeightedDestinationOptions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedDestinationOptions)
	if !ok {
		that2, ok := that.(WeightedDestinationOptions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Extauth.Equal(that1.Extauth) {
		return false
	}
	if !this.BufferPerRoute.Equal(that1.BufferPerRoute) {
		return false
	}
	if !this.StagedTransformations.Equal(that1.StagedTransformations) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
